/**
 * Copyright (c) 2017-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import Link from '@docusaurus/Link';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import withBaseUrl from '@docusaurus/withBaseUrl';

import Layout from '@theme/Layout';


const features = [
    {
        title: <>Overview</>,
        imageUrl: 'img/overview.gif',
        description: (
            <>
                PHYRE provides a set of physics puzzles in a simulated 2D world. Each puzzle has a goal
                state (e.g., make the green ball touch the blue ball) and an initial state in which the
                goal is not satisfied; A puzzle can be solved by placing one or more new bodies in the
                environment such that when the physical simulation is run the goal is satisfied. </>
        ),
    },
    {
        title: <>Templates</>,
        imageUrl: 'img/overview.gif',
        description: (
            <>
                PHYRE is comprised of a series of task templates, where a task template defines a set of
                related tasks that are generated by varying task template parameters (such as positions
                of initial world bodies). All tasks in the same template share a common goal, but have
                different initial world states. Each template defines 100 such tasks, and belongs to a
                tier based on the action space of actions required to solve the tasks. Task templates
                are used to measure an agent’s generalization ability in two settings:
                Within-template: an agent trains on a subset of tasks in the template and is evaluated
                on the remaining tasks within that template.
                Cross-template: an agent trains on tasks in a series of templates and test tasks are
                selected exclusively from templates that were not used for training.</>
        ),
    },
    {
        title: <>Goal</>,
        imageUrl: 'img/goal.gif',
        description: (
            <>
                The goal for all tasks within PHYRE is the same: at the end of the simulation the green
                object must touch the blue or purple object. Agents take actions by placing red objects
                within the scene to achieve the goal. In PHYRE, each color corresponds to a type of
                object: red corresponds to user-added dynamic objects, green and blue represent goal
                dynamic objects, and purple corresponds to a static goal object. Grey corresponds to
                dynamic scene objects, and black to static scene objects.</>
        ),
    },
];



import classnames from 'classnames';

import styles from './styles.module.css';


function Home() {
    const context = useDocusaurusContext();
    const {siteConfig = {}} = context;
    return (
        <Layout
            permalink={'/'}
            description={'Set up a modern web app by running one command.'}
        >
            <div className={classnames('hero hero--primary', styles.heroBanner)}>
                <div className="container">
                    <img
                        className={classnames(styles.heroBannerLogo, 'margin-vert--md')}
                        src={withBaseUrl('img/logo.png')}
                    />
                    <p className="hero__subtitle">{siteConfig.tagline}</p>
                    <div>
                        <Link
                            className={classnames(
                                'button button--outline button--lg',
                                styles.getStarted,
                            )}>
                            Get Started
                        </Link>
                    </div>
                </div>
            </div>
            <div className={styles.lightBackground}>
                <div className="container padding-vert--xl text--left">
                    <div className="row">
                        <div className="col col--4 col--offset-1">
                            <h2 className="text--center">Abstract</h2>
                            <p>
                                Understanding and reasoning about physics is an important ability of intelligent agents.
                                PHYRE is a benchmark for physical reasoning that contains a set of simple classical
                                mechanics puzzles in a 2D enviroment. The benchmark is designed to encourage development
                                of sample-efficient learning algorithms that generalize well across puzzles.
                                <br/>
                                <br/>
                            </p>
                        </div>
                        <div className="col col--5 col--offset-1">
                            <img
                                className={styles.featureImage}
                                alt={'Easy to update'}
                                src={'img/zoom.gif'}
                            />
                        </div>
                    </div>
                </div>
            </div>
            <main>
                {features && features.length && (
                    <section className={styles.features}>
                        <div className="container">
                            <div className="row">
                                {features.map(({imageUrl, title, description}, idx) => (
                                    <div
                                        key={idx}
                                        className={classnames('col col--4', styles.feature)}>
                                        {imageUrl && (
                                            <div className="text--center">
                                                <img
                                                    className={styles.featureImage}
                                                    src={withBaseUrl(imageUrl)}
                                                    alt={title}
                                                />
                                            </div>
                                        )}
                                        <h3 className="text--center">{title}</h3>
                                        <p className="text--center">{description}</p>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </section>
                )}
            </main>
            <div className={styles.lightBackground}>
                <div className="container padding-vert--xl text--left">
                    <div className="row">
                        <div className="col col--4 col--offset-1">
                            <img
                                className={styles.featureImage}
                                alt={'ball'}
                                src={'img/ball.gif'}
                            />
                            <p>
                                Action space includes all valid locations and radii of a single ball.
                                <br/>
                                <br/>
                            </p>
                        </div>
                        <div className="col col--4 col--offset-1">
                        <img
                            className={styles.featureImage}
                            alt={'two_balls'}
                            src={'img/two_balls.gif'}
                        />
                        <p>
                            Action space includes all valid locations and radii of two balls.
                            <br/>
                            <br/>
                        </p>
                    </div>
                    </div>
                </div>
            </div>
        </Layout>
    );
}

export default Home;
